export const GET_ARTICLES = 'GET_ARTICLES'
export const GET_ARTICLE = 'GET_ARTICLE'
export const GET_ARTICLE_LIST = 'GET_ARTICLE_LIST'

export const SET_ARTICLES = 'SET_ARTICLES'
export const SET_ARTICLE = 'SET_ARTICLE'
export const SET_ARTICLE_LIST = 'SET_ARTICLE_LIST'
